SPEC_FUNCTIONS = (
    "Abs",
    "im",
    "re",
    "sign",
    "arg",
    "conjugate",
    "acos",
    "acot",
    "acsc",
    "asec",
    "asin",
    "atan",
    "acosh",
    "acoth",
    "acsch",
    "asech",
    "asinh",
    "atanh",
    "cos",
    "cot",
    "csc",
    "sec",
    "sin",
    "tan",
    "cosh",
    "coth",
    "csch",
    "sech",
    "sinh",
    "tanh",
    "exp",
    "ln",
    "log",
    "sqrt",
    "cbrt",
)
SPEC_SYMBOLS = ["+", "-", "*", "/", "=", "^", "[", "]", "{", "}", "(", ")", "", "."]
BASE_NUMBERS = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
REPLACE_FUNCTIONS = {
    "arccos": "acos",
    "arcsin": "asin",
    "arctan": "atan",
    "arctg": "atan",
    "actg": "atan",
    "cotan": "cot",
    "ctg": "cot",
    "tg": "tan",
}
